### ISSUE TITLE
Dec release checklist

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#80]
- [ ] FGDB to FGDB 
- [ ] EGDB to FGDB
- [ ] FGDB to EGDB
- [ ] EGDB to FS
- [ ] FGDB to FS
- [ ] SHP to FS
- [ ] SHP to EGDB
- [ ] SHP to FGDB
- [ ] Methods not changing field values when sourcename=targetname - #65
- [ ] Try to get layer source even if there is no map - #75 
- [ ] Enterprise GDB data source causing issues - #66 (part of #71 fix)
- [ ] #67/#77 fixes for FactoryCode spatial reference issues. Result was similar error messages to #71 ("Lock or another error"), also improved that error message/processing logic
- [ ] Enterprise GDB preview ignoring rowLimit parameter - #69 
- [ ] 0 source rows could provide a better error message/processing flow - #68
- [ ] Raise an error if source and target layers have the same name when creating a new file - #76
- [ ] Attempt to fix .gitignore to exclude bin/Debug folders - #73 (doesn't work after several attempts)
- [ ] Data Mapper - doesn't reset fields UI when the file updates
- [ ] When Source or Target dataset includes only stock fields, OID, Shape, ShapeLength create file fails -https://github.com/Esri/data-assistant/issues/78
- [ ] Append data completes successfully, but attributes aren't coming through in the target layer #76 
- [ ] Possible memory isses - https://github.com/Esri/data-assistant/issues/79
- [ ] Previous versions of the config files work
- [ ] All process tested in pro 1.3.1
- [ ] All process tested in pro 1.4
- [ ] In a test case where field names match, make sure to run SetValue/other calculation to test field calculator
- [ ] Test with 0 source rows and check messages
- [ ] Include a spatial reference that does not have a FactoryCode
- [ ] Test without a map and with more than 1 map

**Comment by jessnoo** [comment]
Closing as it's out of date. Any items that need to be addressed in December, need to be well documented github issues in the december milestone with a priority status. Standard sanity testing will be handled with the test matrix in box by Esri team.
